name: feature testing

on:
  push:
  workflow_dispatch:

jobs:
  test_features:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files
        uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.10.0

      - name: install node_modules
        run: |
          npm install
          
      - name: test levels
        run: |
          node level1.js
          node level2.js
          node level3.js
          node level4.js
          node level5.js
