name: feature testing

on:
  push:
  workflow_dispatch:

jobs:
  test_features:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files
        uses: actions/checkout@v2
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.10.0
      - name: install node_modules
        run: |
          ls -la
          npm init
          ls -la
          ls node_modules

          # echo hello from the testing script
          # cat package.json
          # npm install chai
          # node --version
          # # cat node_modules/chai/chai.js
          # node level1.js
